[licenses]
version = 2
allow = [
    "Apache-2.0",
    "MIT",
]
exceptions = [
    { allow = ["AGPL-3.0"], name = "forwarder" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip-tree = [
    "windows-sys@0.48",
]
